server:
  port: 8080
  servlet:
    context-path: /aidubbing
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/YOUR_DATABASE_NAME
    username: YOUR_DATABASE_USERNAME
    password: YOUR_DATABASE_PASSWORD
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile

jwt:
  signerKey: "YOUR_JWT_SIGNER_KEY"
  validDuration: 86400
  refreshableDuration: 86400

app:
  upload-dir: YOUR_UPLOAD_DIR
  frontend-redirect-url: http://localhost:3000/auth/callback
  videolingo-dir: YOUR_VIDEOLINGO_DIR
  job-output-dir: YOUR_JOB_OUTPUT_DIR
  python-executable: YOUR_PYTHON_EXECUTABLE_PATH
  sepay:
    bank-account: "YOUR_BANK_ACCOUNT_NUMBER"
    bank-code: "YOUR_BANK_CODE"
    code-prefix: "AIDUB"