server:
  port: YOUR_SERVER_PORT
  servlet:
    context-path: /YOUR_CONTEXT_PATH

spring:
  datasource:
    url: jdbc:postgresql://YOUR_DATABASE_HOST:YOUR_DATABASE_PORT/YOUR_DATABASE_NAME
    username: YOUR_DATABASE_USERNAME
    password: YOUR_DATABASE_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile

jwt:
  signerKey: "YOUR_JWT_SIGNER_KEY"
  validDuration: YOUR_JWT_VALID_DURATION
  refreshableDuration: YOUR_JWT_REFRESH_ABLE_DURATION

app:
  frontend-redirect-url: YOUR_FRONTEND_REDIRECT_URL