server:
  port: 8080
  servlet:
    context-path: /aidubbing
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB

spring:
  datasource:
    url: jdbc:postgresql://YOUR_DB_HOST:YOUR_DB_PORT/aidubbing
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile

jwt:
  signerKey: "YOUR_JWT_SIGNER_KEY"
  validDuration: 86400
  refreshableDuration: 86400

app:
  upload-dir: YOUR_UPLOAD_DIR
  frontend-redirect-url: http://YOUR_FRONTEND_HOST:YOUR_FRONTEND_PORT/auth/callback
  videolingo-dir: YOUR_VIDEOLINGO_DIR
  job-output-dir: YOUR_JOB_OUTPUT_DIR
  upload-audio-dir: YOUR_UPLOAD_AUDIO_DIR
  job-workdir-root: YOUR_JOB_WORKDIR_ROOT
  python-executable: YOUR_PYTHON_EXECUTABLE_PATH
  sepay:
    bank-account: "YOUR_BANK_ACCOUNT"
    bank-code: "YOUR_BANK_CODE"
    code-prefix: "YOUR_CODE_PREFIX"